project_name: osquery_exporter
builds:
  -
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - >
        -s -w
        -X github.com/prateeknischal/osqueryexporter/internal/constants.Version={{ .Version }}
        -X github.com/prateeknischal/osqueryexporter/internal/constants.Build=alpha
        -X github.com/prateeknischal/osqueryexporter/internal/constants.Commit={{ .Commit }}

