name: Docker Image CI

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup version
        id: get-version
        run: |
          echo "::set-output name=version::$(git describe --tags)"
      - name: Push to docker hub
        uses: docker/build-push-action@v1
        with:
          build_args: VERSION=${{ steps.get-version.outputs.version }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kubeir/osquery-exporter
          tag_with_ref: true
